/*
 * generated by Xtext 2.22.0
 */
package xtext.http.rest.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TestSuiteProposalProvider extends AbstractTestSuiteProposalProvider {
}
