/*
 * generated by Xtext 2.22.0
 */
package xtext.http.rest.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TestSuiteUiModule extends AbstractTestSuiteUiModule {

	public TestSuiteUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
