/*
 * generated by Xtext 2.22.0
 */
package xtext.http.rest;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestSuiteRuntimeModule extends AbstractTestSuiteRuntimeModule {
}
