/*
 * generated by Xtext 2.22.0
 */
package xtext.http.rest.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.http.rest.TestSuiteRuntimeModule;
import xtext.http.rest.TestSuiteStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TestSuiteIdeSetup extends TestSuiteStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TestSuiteRuntimeModule(), new TestSuiteIdeModule()));
	}
	
}
